version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./rest_api:/api
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  redis_data:
